repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0

    hooks:
      - id: end-of-file-fixer
        exclude: ^(protomolecule/)
      - id: trailing-whitespace
        exclude: ^(protomolecule/)
      - id: check-merge-conflict
        exclude: ^(protomolecule/)
      - id: debug-statements
        exclude: ^(protomolecule/)
      - id: check-docstring-first
        exclude: ^(protomolecule/)
      - id: check-yaml
        exclude: ^(protomolecule/)
      - id: check-toml
        exclude: ^(protomolecule/)
      - id: check-json
        exclude: ^(protomolecule/)
      - id: name-tests-test
        exclude: ^(protomolecule/)
      - id: check-xml
        exclude: ^(protomolecule/)
      - id: check-symlinks
        exclude: ^(protomolecule/)
      - id: requirements-txt-fixer
        exclude: ^(protomolecule/)
      - id: detect-aws-credentials
        exclude: ^(protomolecule/)
      # - id: flake8
      #   additional_dependencies:
      #     [
      #       flake8-blind-except,
      #       flake8-bugbear,
      #       flake8-comprehensions,
      #       flake8-debugger,
      #       flake8-docstrings,
      #       flake8-isort,
      #       flake8-polyfill,
      #       flake8-pytest,
      #       flake8-quotes,
      #       yesqa,
      #     ]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       exclude: ^docs/conf.py
  #       args: [--no-strict-optional, --ignore-missing-imports]

  # - repo: https://github.com/psf/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black
  #       exclude: ^(protomolecule/)
  #       language_version: python3.9

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        exclude: ^(protomolecule/)
        args: [--py36-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(protomolecule/)
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        exclude: ^(protomolecule/)

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      # - id: python-check-blanket-noqa
      # - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
        exclude: ^(protomolecule/)
      - id: python-no-eval
        exclude: ^(protomolecule/)
      - id: python-no-log-warn
        exclude: ^(protomolecule/)
      - id: rst-backticks
        exclude: ^(protomolecule/)
      - id: rst-directive-colons
        exclude: ^(protomolecule/)
      - id: rst-inline-touching-normal
        exclude: ^(protomolecule/)
      - id: text-unicode-replacement-char
        exclude: ^(protomolecule/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.13
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
